xKylee/plugins-source

grotesqueguardians/grotesqueguardians.gradle.kts, grotesqueguardians/src/main/java/net/runelite/client/plugins/grotesqueguardians/GrotesqueGuardiansPlugin.java
changed gaurdians to guardians
=> Guardians: spellcheck

nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
Changed the logic for curse detection.
=> PR: Nightmare fix

menuentryswapperextended/menuentryswapperextended.gradle.kts
=> mesextended: fix

buildSrc/src/main/kotlin/Dependencies.kt
=> version: update

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
=> Mesextended fix rc swaps

nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
Nightmare: fix broken commit
this broke cursed phase.
=> Nightmare: fix broken commit

nightmare/nightmare.gradle.kts
=> nightmare: force update

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
=> mes: fix rc crashing client

buildSrc/src/main/kotlin/Dependencies.kt
=> version: bump to 1.6.9

demonicgorilla/demonicgorilla.gradle.kts, demonicgorilla/src/main/java/net/runelite/client/plugins/demonicgorilla/DemonicGorillaPlugin.java
=> demonicgorillas: bump

dropparty/dropparty.gradle.kts, dropparty/src/main/java/net/runelite/client/plugins/dropparty/DropPartyConfig.java, dropparty/src/main/java/net/runelite/client/plugins/dropparty/DropPartyOverlay.java, dropparty/src/main/java/net/runelite/client/plugins/dropparty/DropPartyPlugin.java
=> dropparty: fix

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
mesextended: lava fix + crafting tele support
=> mesextended: lava fix + crafting tele support

build.gradle.kts
=> project: update info

neverlog/neverlog.gradle.kts
=> Neverlog: update

neverlog/neverlog.gradle.kts
=> neverlog: typo

playerscouter/src/main/java/net/runelite/client/plugins/playerscouter/PlayerContainer.java, playerscouter/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java, playerscouter/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouterConfig.java
=> playerscouter: revert

prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PlayerContainer.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerConfig.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlay.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlayPrayerTab.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerPlugin.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/WeaponType.java
=> prayagainstplayer: revert

neverlogout/neverlogout.gradle.kts
=> neverlog: fix gradle

buildSrc/src/main/kotlin/Dependencies.kt, neverlogout/neverlogout.gradle.kts
=> project: add kotlinversion

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/MESAbstractComparables.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/PrioParse.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/BurningAmuletMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/CombatBraceletMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/ConstructionMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/DigsitePendantMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/DuelingRingMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/GamesNecklaceMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/GloryMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/NecklaceOfPassageMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/RingOfWealthMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/SkillsNecklaceMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/SlayerRingMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/XericsTalismanMode.java
added left click trade and left click follow
cleaned up code
removed left click report
=> mesextended: tidyup and more

hideunder/hideunder.gradle.kts, hideunder/src/main/java/net/runelite/client/plugins/hideunder/HideUnder.java
=> hideunder: fix

cerberus/cerberus.gradle.kts, cerberus/src/main/java/net/runelite/client/plugins/cerberus/domain/CerberusNPC.java, coxhelper/coxhelper.gradle.kts, coxhelper/src/main/java/net/runelite/client/plugins/coxhelper/CoxInfoBox.java, dynamicmaxhit/dynamicmaxhit.gradle.kts, dynamicmaxhit/src/main/java/net/runelite/client/plugins/dynamicmaxhit/Utils.java, theatre/src/main/java/net/runelite/client/plugins/theatre/rooms/BloatHandler.java, theatre/theatre.gradle.kts
=> fix broken plugins

tobdamagecount/src/main/java/net/runelite/client/plugins/tobdamagecount/TobDamageCounterPlugin.java, tobdamagecount/tobdamagecount.gradle.kts
=> tobdamagecount: fix

build.gradle.kts
=> fix rxrelay

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/src/main/java/net/runelite/client/plugins/theatre/rooms/MemorizedTornado.java, theatre/src/main/java/net/runelite/client/plugins/theatre/rooms/VerzikHandler.java, theatre/theatre.gradle.kts
Adds a feature that highlights the purple tornadoes on spawn, and will stop highlighting them if they are not targeting you.
=> theatre: add tornado tracking feature

inferno/inferno.gradle.kts, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoSpawnTimerInfobox.java
* Increment plugin version to 0.0.12
* Add config toggle for spawn timer infobox
* Clean up onNpcSpawned and onNpcDespawned methods
=> inferno: add spawn set timer infobox

effecttimers/effecttimers.gradle.kts, effecttimers/src/main/java/net/runelite/client/plugins/effecttimers/EffectTimersConfig.java, effecttimers/src/main/java/net/runelite/client/plugins/effecttimers/EffectTimersOverlay.java, effecttimers/src/main/java/net/runelite/client/plugins/effecttimers/FontStyle.java, effecttimers/src/main/java/net/runelite/client/plugins/effecttimers/Timer.java, effecttimers/src/test/java/net/runelite/client/plugins/effecttimers/EffectTimersOverlayTest.java
1) Set Colors - Should we set our own timer colors regardless of showing/not showing icons
2) Font Style - Choose between Italics, Bold and Normal.
3) Text Size - speaks for itself really.
4) Time - choose between MM:SS:MM, TICKS and Seconds.
=> effecttimers: lots of goodies

prayagainstplayer/prayagainstplayer.gradle.kts, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlay.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerOverlayPrayerTab.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/PrayAgainstPlayerPlugin.java, prayagainstplayer/src/main/java/net/runelite/client/plugins/prayagainstplayer/WeaponType.java
Reverts xKylee/plugins-source#106
=> Revert "prayagainstplayer: redo prayer logic"

gauntlet/gauntlet.gradle.kts, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletConfig.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletInfoBoxOverlay.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletOverlay.java
Re-organized, re-worded ambiguity, removed un-used options, fixed spelling errors, condensed options.
=> gauntlet: clean up config

coxhelper/coxhelper.gradle.kts, coxhelper/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
Reverts xKylee/plugins-source#135
=> Revert "coxhelper: fix olm attack prediction"

coxhelper/coxhelper.gradle.kts, coxhelper/src/main/java/net/runelite/client/plugins/coxhelper/CoxPlugin.java
Reverts xKylee/plugins-source#137
=> Revert "coxhelper: add extra tick"

aoewarnings/aoewarnings.gradle.kts, aoewarnings/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, aoewarnings/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningPlugin.java
So the ratatat indicators stop fucking up your woox walk
=> aoewarnings: Enable individual control over vorkath aoe warnings

hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreConfig.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreGameObject.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreIDs.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
=> HallowedSepulchre: refactor

build.gradle.kts, hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreConfig.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreIDs.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
- adds reset utilization to ensure data sets are properly cleared out
- adds a check to see if player is in the sepulchre or not (eventually want to do a region check to replace this, but that's a lot of regions..)
- adds font-size config option for the wizard statues
- fixes the misspelled reset method name
Still much more needing to be done. To be continued.
=> Sepulchre Enhancements

castlewarsextended/castlewarsextended.gradle.kts, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/Barricade.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/CastleWarsExtendedConfig.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/CastleWarsExtendedPlugin.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/GameTimeOverlay.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/MinimapOverlay.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/SceneOverlay.java, castlewarsextended/src/main/java/net/runelite/client/plugins/castlewarsextended/TindTimerOverlay.java, settings.gradle.kts
cwarsextended: free plugin cause t7x was a cunt.
=> cwarsextended: free plugin cause t7x was a cunt.

hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
Overlay wasn't being added if plugin was enabled while logged out
=> hallowedsepulchre: add overlay to overlaymanager

hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreConfig.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
Moved region check logic out of onGameTick and into onGameState
Added render distance
=> hallowedsepulchre: updates

hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
sepulchre: fix ticks on wizard objects
=> sepulchre: fix ticks on wizard objects

hallowedsepulchre/hallowedsepulchre.gradle.kts, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreConfig.java, hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java
Same option found in Tile Indicators, but I don't think everyone is aware of it or that it is OP at sepulchre.
=> hallowedsepulchre: add highlight player tile

gauntlet/gauntlet.gradle.kts, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletConfig.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayMain.java
*slaps roof of plugin* this baby can fit so many damn overlays
Someone wanted outline-only resources.
=> gauntlet: resource outline

gauntlet/gauntlet.gradle.kts, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletConfig.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/entity/Resource.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayGauntlet.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayHunllefRoom.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayPrayerBox.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayPrayerWidget.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayTimer.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/resource/InfoboxResourceCounter.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/resource/ResourceTracker.java
* Add resource infobox tracker
* Refactor OverlayMain into OverlayGauntlet and OverlayHunllefRoom classes
* Add singleton annotation to injected classes
* Change config name to lowercase
* Change plugin type from PVM to Minigame
* Bump version to 0.1.4
=> gauntlet: resource tracker

gauntlet/gauntlet.gradle.kts, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletConfig.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/entity/Hunllef.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayGauntlet.java, gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/overlay/OverlayHunllef.java
* Add a config to flash screen when using 5:1 method
* Revert previous commit due to Jagex hotfix
=> gauntlet: flash on 5:1 method

environmentaid/environmentaid.gradle.kts, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidConfig.java, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidPlugin.java
environmentaid: add zammy and snow options
=> environmentaid: add zammy and snow options

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/src/main/java/net/runelite/client/plugins/theatre/rooms/MaidenHandler.java, theatre/theatre.gradle.kts
=> theatre: add maiden healer distance

environmentaid/environmentaid.gradle.kts, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidConfig.java, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidPlugin.java
=> Environmentaid

multiindicators/multiindicators.gradle.kts, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MapLocations.java
Corrected Kourend zones (changed due to continent rework) and added missing bank safe zones
=> Multiindicators: update zones

fightcave/fightcave.gradle.kts, fightcave/src/main/java/net/runelite/client/plugins/fightcave/FightCavePlugin.java
added "and what to pray at TzTok-Jad" after the current description to make it a little clearer than it shows what to pray aswell
=> made the description clearer

playerattacktimer/playerattacktimer.gradle.kts, playerattacktimer/src/main/java/net/runelite/client/plugins/playerattacktimer/PlayerAttackTimerPlugin.java
reverting to checking animation on gametick because it wasn't working with blowpipe
=> playerattacktimer: check animation onGameTick

nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmareConfig.java, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmareOverlay.java, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
This update will draw a box around whoever is targeted with the husk special attack, it will highlight nightmare in orange during the shadow portal attack as standing under her is dangerous, and it will highlight the nightmare's hitbox of her charge attack.
=> nightmare: update nightmare plugin 

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/ConstructionMode.java
=> mese: add attackstone

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/teleportmode/ConstructionMode.java
=> mese: attack stones

alchemicalhydra/alchemicalhydra.gradle.kts, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraConfig.java, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/overlay/SceneOverlay.java
* Add lightning overlay
* Add 'Special Attack' config section
* Add config to toggle poison overlay
* Add config to toggle lightning overlay
=> alchemicalhydra: updates

theatre/theatre.gradle.kts
=> theatre: bump

theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/Bloat.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/BloatOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Maiden/Maiden.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Maiden/MaidenOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NyloNPC.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NyloSelectionBox.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NyloSelectionManager.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/Nylocas.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NylocasAliveCounterOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NylocasOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/RoomOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Sotetseg/Sotetseg.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Sotetseg/SotetsegOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Verzik/Verzik.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Verzik/VerzikOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/XarpusOverlay.java, theatre/theatre.gradle.kts
project clean up
mirror mode support
mes fix
=> theatre: various

theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/Nylocas.java, theatre/theatre.gradle.kts
=> theatre: better mes handling

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/theatre.gradle.kts
fix config
fix xarpus instance timer
=> tob: update

wildernesslocations/src/main/java/net/runelite/client/plugins/wildernesslocations/WildernessLocationsMapOverlay.java, wildernesslocations/wildernesslocations.gradle.kts
Future changes to the map overlay in order to function in line with WorldLocation rework.
**Should be implemented after open-osrs/runelite#2796 is merged.**
=> WildernessLocations: MapOverlay

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/theatre.gradle.kts
theatre: remove awful while loop
fuck you Damen
=> theatre: remove awful while loop

playerscouter/playerscouter.gradle.kts, playerscouter/src/main/java/net/runelite/client/plugins/playerscouter/PlayerScouter.java
=> playerscouter: fix

ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersPlugin.java, ticktimers/ticktimers.gradle.kts
ticktimers: update for instanced sara
=> ticktimers: update for instanced sara

theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/Bloat.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/Nylocas.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NylocasOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Room.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Sotetseg/Sotetseg.java, theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Verzik/Verzik.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/XarpusOverlay.java, theatre/theatre.gradle.kts
+ nylo menu entry swap so you can only hit the purple crab with trident of the swamp, BP, tent whip, or any serp helm equipped
+ ability to hide the bloat tank chamber in the middle of the room as well as the hanging chains
+ ability to add a tick timer to the spawns of the nylo room in order to know when the next wave might spawn
=> theatre: theatre updates

npcstatus/npcstatus.gradle.kts
=> npc status: fix

multiindicators/multiindicators.gradle.kts, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MapLocations.java, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsConfig.java, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsMinimapOverlay.java, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsOverlay.java, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MultiIndicatorsPlugin.java
Someone in the discord requested this feature plus I agree and I had a little time to kill so yh
:_P
=> Multiindicators: Wilderness teleport lines

gauntlet/src/main/java/net/runelite/client/plugins/gauntlet/GauntletPlugin.java
fixes gauntlet so it queries game objects and pushes them to ongameObjectSpawned.
=> Gauntlet fix addSpawnedEntities query

blackjack/blackjack.gradle.kts, blackjack/src/main/java/net/runelite/client/plugins/blackjack/BlackjackPlugin.java
=> blackjack: fix blackjack

inferno/inferno.gradle.kts, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
Inferno - use Open npcmanager instead of RL
I wonder if this is a problem anywhere else
=> Inferno - use Open npcmanager instead of RL

inferno/inferno.gradle.kts, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java
Inferno: 6 Jad Challenge support - New IDs
and version bump
=> Inferno: 6 Jad Challenge support - New IDs

socketsotetseg/socketsotetseg.gradle.kts, socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegConfig.java, socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegOverlay.java, socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegPlugin.java
+ Config for removal of the screen flash
+ Add a custom message for a custom amount of time on the screen when chosen
=> socketsotetseg: add option to have chosen text pop up

environmentaid/environmentaid.gradle.kts, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidConfig.java, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidPlugin.java
environmentaid: remove scrypool effect
ty for the idea Buff.
=> environmentaid: remove scrypool effect

blackjack/blackjack.gradle.kts, blackjack/src/main/java/net/runelite/client/plugins/blackjack/BlackjackPlugin.java
blackjack: hopefully stop having to turn off attack options
=> blackjack: hopefully stop having to turn off attack options

menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/ConstructionMode.java
=> Mesx construction

specorb/specorb.gradle.kts, specorb/src/main/java/net/runelite/client/plugins/specorb/SpecOrbPlugin.java
=> Specorb: fix npe

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/ConstructionMode.java
=> mesx: fix mythical capes

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
=> mesx: eternal glory support

buildSrc/src/main/kotlin/Dependencies.kt, menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/ConstructionCapeMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/CraftingCapeMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/MagicCapeMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/MaxCapeEquippedMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/XericsTalismanMode.java
Added
Crafting Cape (equipped & inventory)
Construction Cape (equipped & inventory)
Magic Cape (equipped & inventory)
*Max Cape (equipped)
Changed
*Xeric's Talisman
*Not all menu entries can be swapped with the plugin currently, added/removed to only those which are currently supported.
=> mesx: added more swaps

alchemicalhydra/alchemicalhydra.gradle.kts, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraPlugin.java, buildSrc/src/main/kotlin/Dependencies.kt, cerberus/cerberus.gradle.kts, cerberus/src/main/java/net/runelite/client/plugins/cerberus/CerberusPlugin.java, dagannothkings/dagannothkings.gradle.kts, dagannothkings/src/main/java/net/runelite/client/plugins/dagannothkings/DagannothKingsPlugin.java, fightcavespawnrotation/fightcavespawnrotation.gradle.kts, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/FightCavesSpawnRotationConfig.java, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/FightCavesSpawnRotationPlugin.java, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/overlay/FightCavesDisplayOverlay.java, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/overlay/FightCavesRotationOverlay.java, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/util/FightCavesSpawnLocations.java, fightcavespawnrotation/src/main/java/net/runelite/client/plugins/fightcavespawnrotation/util/FightCavesStartLocations.java, grotesqueguardians/grotesqueguardians.gradle.kts, grotesqueguardians/src/main/java/net/runelite/client/plugins/grotesqueguardians/GrotesqueGuardiansPlugin.java
alchemical hydra: fix having to restart plugin after each trip
cerberus: fix having to restart plugin after each trip
groteque guardians: fix having to restart plugin after each trip
dagannoth kings: fix having to restart plugin after each trip
fight cave spawn predictor: fix issue with overlay not rendering
=> project: various fixes

multiindicators/multiindicators.gradle.kts, multiindicators/src/main/java/net/runelite/client/plugins/multiindicators/MapLocations.java
Add new safe zone location introduced with latest update
Corrected comment/location on 2 entries
=> multiindicators: add new locations

aoewarnings/aoewarnings.gradle.kts, aoewarnings/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java
Idk why someone asked for it but they did so here I am.
=> Lower min font size for AoE warnings

buildSrc/src/main/kotlin/Dependencies.kt, nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java, wildernesslocations/src/main/java/net/runelite/client/plugins/wildernesslocations/WildernessLocationsPlugin.java, wildernesslocations/wildernesslocations.gradle.kts
=> Nightmare: fix death anim

nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
the event doesn't seem to fire correctly after the first kill, so check if nm is null && id == 9425 for now
=> Nightmare patch

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/CustomSwapParse.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/PrioParse.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/AbstractComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/BankComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/BaseComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/ComparableEntries.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/EquipmentComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/InventoryComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/ItemComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/ShopComparableEntry.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/comparableentry/WithdrawComparableEntry.java
Implement the old Custom swaps and Prioritize entry
Still one issue: The text labels 'Custom Swaps' and 'Prioritize Entry' aren't visible in the config. Seems like an issue in ConfigPanel.java
https://imgur.com/a/a7Ek3yU
=> menuentryswapperextended: Implement custom swaps and prioritize entry

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/XarpusOverlay.java, theatre/theatre.gradle.kts
Fixes exhumeds count being incorrect due to a bugged runelite event (onGroundObjectSpawned fires twice sometimes)
+ Exhumeds count down instead of up
=> Theatre: Xarpus exhumeds rework

socketdeathindicator/socketdeathindicator.gradle.kts, socketdeathindicator/src/main/java/net/runelite/client/plugins/socketdeathindicator/SocketDeathIndicatorPlugin.java
socketdeathindicator stops working sometimes, this fixes the issue
=> socketdeathindicator: fix stops working

theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/BloatOverlay.java, theatre/src/main/java/net/runelite/client/plugins/theatre/TheatreConfig.java, theatre/theatre.gradle.kts
Some people were used to it counting up, and would like the option of changing it back.
=> theatre: add config option for bloat counting style

theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java, theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/XarpusOverlay.java, theatre/theatre.gradle.kts
This reverts some of my previous changes and uses a better method to avoid the bugged runelite event
=> Theatre: Xarpus exhumeds fix

socketsotetseg/socketsotetseg.gradle.kts, socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegPlugin.java
Thanks to caps lock13#0001 for helping me update
Maze solve only works in overworld in this update
=> socketsotetseg: update to support sm/hm

nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmareOverlay.java, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
also removed the confusing method of clearing the shadows
=> Nightmare: show shadow special as nightmare attack

inferno/inferno.gradle.kts, inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
The calculation did not update the distance and count values every iteration. Now correctly calculates and updates as the nibblers move.
=> inferno: fix central nibbler calculation

alchemicalhydra/alchemicalhydra.gradle.kts, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraConfig.java, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraPlugin.java, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/overlay/SceneOverlay.java
Hydra: add fountain ticks + overlay
shows hydra fountain ticks at all time so you can decide if you should bp/tbow between phases.
Should also show while hydra is dead so you can decide what to do when a new hydra spawns. (tbh didnt test this as I have no task :( )
=> Hydra: add fountain ticks + overlay

alchemicalhydra/alchemicalhydra.gradle.kts, alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraPlugin.java
Hydra : Use Dynamic objects to track fountain ticks. Its more accurate.
=> Hydra : Use Dynamic objects to track fountain ticks

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
mesx: add - hide attack, hide examine, hide destroy, hide cast players raids, hide cast thralls, hide loot implings
=> mesx: add features

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/DiaryCapeMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/FarmCapeMode.java, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/QuestCapeMode.java
+ Adds swaps for Diary cape, Farming cape, and Quest cape.
=> Add more Cape swaps

environmentaid/environmentaid.gradle.kts, environmentaid/src/main/java/net/runelite/client/plugins/environmentaid/EnvironmentAidPlugin.java
use local player region instead of first region in client.getMapRegions()[0]
=> environmentaid: fix underwater + snow region checks

aoewarnings/aoewarnings.gradle.kts, aoewarnings/src/main/java/net/runelite/client/plugins/aoewarnings/AoeWarningConfig.java, aoewarnings/src/main/java/net/runelite/client/plugins/aoewarnings/BombOverlay.java, buildSrc/src/main/kotlin/Dependencies.kt
Adds heatmap for olm crystal bombs
=> aoewarnings: add olm crystal bomb heatmap

menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/CustomSwaps.java
makes it so the plugin works with the new API changes
=> mesx: fix priority

zulrah/src/main/java/net/runelite/client/plugins/zulrah/overlays/SceneOverlay.java, zulrah/zulrah.gradle.kts
=> zulrah: add next stall overlay

nex/nex.gradle.kts, nex/src/main/java/net/runelite/client/plugins/nex/NexConfig.java, nex/src/main/java/net/runelite/client/plugins/nex/NexOverlay.java, nex/src/main/java/net/runelite/client/plugins/nex/NexPlugin.java
**changelog 5.0.7**
- lower click delay after dash
- hide range indicator during dash
- remove pray swap indicator as who tf knows
- tank indicator now resets to 4 after interaction change
- make outlining less harsh with feather setting in config
=> nex: 5.0.7

aoewarnings/aoewarnings.gradle.kts, coxhelper/coxhelper.gradle.kts
=> project: bump some plugin versions

nex/nex.gradle.kts, nex/src/main/java/net/runelite/client/plugins/nex/NexPlugin.java
My very great friend in discord told me these values.
=> nex: 5.0.9 Strike these values, very roughly!

buildSrc/src/main/kotlin/Dependencies.kt, effecttimers/effecttimers.gradle.kts, fightcave/fightcave.gradle.kts, fightcave/src/main/java/net/runelite/client/plugins/fightcave/FightCaveContainer.java, fightcave/src/main/java/net/runelite/client/plugins/fightcave/FightCavePlugin.java, hideunder/hideunder.gradle.kts, hideunder/src/main/java/net/runelite/client/plugins/hideunder/HideUnderConfig.java, hideunder/src/main/java/net/runelite/client/plugins/hideunder/HideUnderPlugin.java, menuentryswapperextended/menuentryswapperextended.gradle.kts, menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java, ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/NPCContainer.java, ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersPlugin.java, ticktimers/ticktimers.gradle.kts
bump effect timers
remove npcmanager dependancy due to wrong scraping causing issues on fight caves and tick timers.
rework hideunder
=> project: npcmanager removal + hideunder config rework + effect timers rebuild

buildSrc/src/main/kotlin/Dependencies.kt, entityfocuspile/entityfocuspile.gradle.kts, entityfocuspile/src/main/java/net/runelite/client/plugins/entityfocuspile/EntityFocusPilePlugin.java, nightmare/nightmare.gradle.kts, nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
=> playergetid -> getid

buildSrc/src/main/kotlin/Dependencies.kt, hideunder/hideunder.gradle.kts, hideunder/src/main/java/net/runelite/client/plugins/hideunder/HideUnderConfig.java, hideunder/src/main/java/net/runelite/client/plugins/hideunder/HideUnderPlugin.java
=> entity hider: rework
