xKylee/plugins-source

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedConfig.java
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
Removes the menu entry swappers hide lookup option as its already located inside hiscores, https://i.imgur.com/40T9H2k.jpg
> Remove: mesex.java lookup

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoOverlay.java
I have added an option to always show the prayer helper even when the prayer widget is hidden.
This is defaulted to `false` as to keep the old functionality as the default.
Here's an exmaple: https://gyazo.com/20ac9a6fc6865490b594a370ab4bb8b0.
It seems that `getWidget` will return `null` upon login, until you open the prayer widget once.
On login players will have to open the prayer widget once and then the helper will never be hidden.
> inferno: add option to always show prayer helper

- nightmare/nightmare.gradle.kts
- nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmareConfig.java
- nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmareOverlay.java
- nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
This PR adds the option for a basic red tick timer to display on the current player if they have been infected by a parasite during the nightmare fight. Features:
- Will start to count down from 21 ticks if the user has been infected by a parasite, with the ticks drawn on the player.
- Will end when the parasite has spawned.
A fancier method for showing the countdown until parasite spawn (as mentioned in #53) is entirely possible, but I will have to leave it for someone else who is better with making those kinds of overlays.
> nightmare: add parasite tick timer option

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/displaymodes/InfernoZukShieldDisplayMode.java
This PR implements the inferno shield predict and live + predict options. As indicated in the config description, the predicted shield will only start showing once the shield has moved one complete rotation because of the way the predicted safespots are calculated.
> inferno: add inferno shield predict and live plus predict options

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
There was an issue where the predicted safespot might be a little bit off immediately after the healers spawned. While this would correct itself within 1-2 Zuk attacks, it could cause the user to stand in the wrong spot and take a hit from Zuk. This PR should mitigate that issue.
> inferno: improve shield prediction accuracy

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
While doing additional testing of the inferno predicted shield, I discovered that Zuk decides whether or not to target you when the tick counter hits "7" (after healers) or "10" (before healers), not "1" as is commonly assumed. I have modified the predicted safespot calculations accordingly.
> inferno: improve predicted shield accuracy

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
Shifted the pre-healers predicted safespot behind by 1 tile, which should now make it 100% accurate when it is shown. This is because Zuk attacks when the counter says "1" pre-healers, but "7" post-healers. Thanks to @dutta64 for the heads up about this.
> inferno: improve pre-healers predicted safespot accuracy

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
Immediately after healers spawn, the ticksTillNextAttack is not accurate. By setting it to a negative va;ie, it will be allowed to update immediately after the next Zuk attack animation, and it won't render the predicted safespot until it is 100% sure of where it is safe.
> inferno: hide predicted safespots post-healers until ticksTillNextAttack is synced

- lizardmenshaman/lizardmenshaman.gradle.kts
- lizardmenshaman/src/main/java/net/runelite/client/plugins/lizardmenshaman/LizardmanShamanOverlay.java
This adds support for shaman spawns in the canyon location, which had an increased explosion radius compared to molch dungeon/temple (5x5 vs 3x3).
> lizardman shamans: add increased radius support

- hallowedsepulchre/hallowedsepulchre.gradle.kts
- hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreConfig.java
- hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreIDs.java
- hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java
- hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchrePlugin.java
This also reverts the onGameStateChanged handling back to where the lists of objects will be cleared on every LOADING event. This inadvertently was preventing [this issue](https://i.imgur.com/lraVOwf.gifv) I think... a proper fix will need to be made, but for now clearing on load doesn't cause any issues in the minigame, from what I've tested.
> hallowedsepulchre: region checking

- hallowedsepulchre/hallowedsepulchre.gradle.kts
- hallowedsepulchre/src/main/java/net/runelite/client/plugins/hallowedsepulchre/HallowedSepulchreOverlay.java
There's a slight bug where the crossbow statue would get stuck and stay highlighted even when it was done firing, it appears to be due to gameObject animationIds not updating properly if the statue is too far away. This PR should mitigate that issue without negatively impacting the experience, since the projectile will have left the statue already by the time the statue is de-highlighted.
> sepulchre: expand crossbow statue de-highlight cases

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
"hide empty" option for potions now works properly with Saradomin brew, Super restores and more
> mesextended: fixed bad spelling

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
By waiting 3 ticks after healers spawn to set the predicted safespot, the edge case where the predicted safespots (and tick counter) becomes messed up if the healers spawn on or around the same tick that Zuk attacks can be avoided.
Unfortunately, this does result in a slightly longer delay before you are able to use the predicted safespots post-healers, but I believe it is necessary because it should properly handle all cases (instead of handling most cases well, and some cases badly like it did before). It might be possible to get the best of both worlds with some additional adjustments, but that will have to be for another PR.
> inferno: wait 3 ticks after healers spawn before setting predicted safespot

- ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/NPCContainer.java
- ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersConfig.java
- ticktimers/src/main/java/net/runelite/client/plugins/ticktimers/TickTimersPlugin.java
- ticktimers/ticktimers.gradle.kts
ticktimers: cleanup
remove DK functionality due to DK's being in their own plugin.
> ticktimers: cleanup

- settings.gradle.kts
- sorceressgarden/sorceressgarden.gradle.kts
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressGardenConfig.java
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressGardenOverlay.java
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressGardenPlugin.java
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressSession.java
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressSqirkOverlay.java
- sorceressgarden/src/main/java/net/runelite/client/plugins/sorceressgarden/SorceressSqirks.java
This plugin provides various utilities for the Sorceress' Garden minigame.
**Features:**
- Show how many sqi'rks the player has picked, and their rate of picking per hour
- Show which sqi'rks the player has picked
- Show the safespot tiles to the sqi'rk trees within each garden
- Highlight the elementals in each garden
- Show "one-clicking" indicators:
- For the winter garden, this provides the user with an indicator for where to stand and when to click on the sq'irk tree
- For the summer garden, this provides the user with an indicator for where to stand, an indicator for when the bottom-most elementals are "in sync", and an indicator for when to click on the sq'irk tree
**Example of the Summer Garden one-click indicators:**
**Dependencies:**
- XPTracker
**Notes:**
There are a few things …
> SorceressGarden: Add plugin

- socketdeathindicator/socketdeathindicator.gradle.kts
- socketdeathindicator/src/main/java/net/runelite/client/plugins/socketdeathindicator/SocketDeathIndicatorPlugin.java
- socketdeathindicator/src/main/java/net/runelite/client/plugins/socketdeathindicator/SocketDeathIndicatorsConfig.java
- socketdeathindicator/src/main/java/net/runelite/client/plugins/socketdeathindicator/SocketDeathIndicatorsOverlay.java
- remove hiding of menu entries since it was a bootleg fix in the first place
- remove highlighting dead nylos 
- add the cleanup for the NPCs indices in the client array list, this was causing issues because when I wasn't cleaning up the array, if another NPC spawned with the same index as a nylo that was killed in nylo it would not render on the screen.
> socketdeathindicators: fix for hiding unwanted npcs

- theatre/src/main/java/net/runelite/client/plugins/theatre/Nylocas/NylocasWave.java
- theatre/theatre.gradle.kts
The goal of this PR is to fix the overlay during Nylo waves as there are small discrepancies with spawn location.
Specific issues encountered so far:
> fix nylo overlay typo

- nightmare/nightmare.gradle.kts
- nightmare/src/main/java/net/runelite/client/plugins/nightmare/NightmarePlugin.java
#369 did not fix the issue.
9425 ID is used throughout P1, not on subsequent kills, this causes the tick counter to constantly reset during P1
#323 why was this even moved to onAnimationChanged?
> Nightmare: actually fix

- theatre/src/main/java/net/runelite/client/plugins/theatre/TheatrePlugin.java
- theatre/src/main/java/net/runelite/client/plugins/theatre/Xarpus/Xarpus.java
- theatre/theatre.gradle.kts
Currently the Xarpus instance timer is incorrect by 1tick (correct tick to enter is 3 instead of 0)
Moving the instance timer trigger from GameTick to ClientTick fixes the issue (now enter on 0 as intended)
> Xarpus instance timer

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
This fixes the issue where only the last priority entry of all entries with the same option was used.
> menuentryswapperrextended: Priority entries fix

- socketsotetseg/socketsotetseg.gradle.kts
- socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegPlugin.java
Sometimes the chosen flag is incorrectly set when you are NOT chosen, this occurs AFTER you have previously been chosen.
I believe this is due to the widget text not always being cleared.
This is a bug on RuneLite too (seems completely random when it happens)
> Socket Sotetseg: Fix chosen

- spellbook/spellbook.gradle.kts
- spellbook/src/main/java/net/runelite/client/plugins/spellbook/SpellbookPlugin.java
Correct varbit to get which spellbook.
This was converted wrong as part of 4.0 updates and changing plugins from using Varbits.SPELLBOOK back to just the varbit id.
> Spellbook: Correct varbit for getting current spellbook

- theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/Bloat.java
- theatre/src/main/java/net/runelite/client/plugins/theatre/Bloat/BloatOverlay.java
- theatre/theatre.gradle.kts
Makes the tick counter count down when bloat is down instead of counting up.
Makes it easier to see when bloat will rise.
> Theatre: Bloat count down instead of up when bloat is in down state

- socketdeathindicator/socketdeathindicator.gradle.kts
- socketdeathindicator/src/main/java/net/runelite/client/plugins/socketdeathindicator/SocketDeathIndicatorPlugin.java
Previous fix was supposed to contain "&& !Objects.equals(r.isHidden(), true)" but that method doesn't work with "tob health bars" from the plugin hub anyway.
> socketdeathindicator: rework party

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
Fixes conflicts with builtin plugins such as:
* Chat history right click copy to clipboard
* Inventory tags
Race condition fix - new entries were already added before mesx onMenuOpened fired, therefore event entries were already invalid.
> mesx: fix right click menu conflicts with builtins

- buildSrc/src/main/kotlin/Dependencies.kt
- socketsotetseg/socketsotetseg.gradle.kts
- socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/MazeTrueTileOverlay.java
- socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegConfig.java
- socketsotetseg/src/main/java/net/runelite/client/plugins/socketsotetseg/SotetsegPlugin.java
This adds a true tile overlay to sotetseg. The maze overlay renders over the true tile from tile indicators, and you can't turn the border off. This was based off of https://github.com/c13-c/Socket/blob/012a09c2518846260e9b3770ebe8220520eb7c2d/plugins/src/main/java/net/runelite/client/plugins/socket/plugins/sotetseg/MazeTrueTileOverlay.java
> Add true tile to socket sotetseg

- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/XericsTalismanMode.java
Hey Kyle,
I believe I've fixed up a few issues here:
1. the xeric's talisman changed the lookout teleport name from look-out to lookout
2. made it so when you have an item unticked in the config it will no longer enable the swap
3. fixed the bug where its not loading swaps unless starting up the plugin while logged in
also had a look into the xeric's talisman "xeric's honour" teleport couldnt figure out how to fix it however noticed the "wintertodt camp" games neck teleport had the same issue. i dont have a skills neck on my only account (ironman) so i couldn't test that (since its another item with 5+ teleports). might have a go with the kourend book teleport one day since that has 5 too.
Hope this helps!
Cheers
James
> mesx: bug fixes

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/CustomSwaps.java
Remove options and hotkey swaps weren't working on startup due to me being a dumby but I fixed it.
> MESX: Fix remove and hotkey swaps

- menuentryswapperextended/menuentryswapperextended.gradle.kts
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/MenuEntrySwapperExtendedPlugin.java
- menuentryswapperextended/src/main/java/net/runelite/client/plugins/menuentryswapperextended/util/CustomSwaps.java
this makes it so that mesx is able to swap menu entries that get added using the clientTick event.
> mesx: change priority for client tick event

- specorb/specorb.gradle.kts
- specorb/src/main/java/net/runelite/client/plugins/specorb/SpecOrbPlugin.java
Plugin no longer adds a menu option when the mouse leaves the screen and runelite sets mouse and orb locations to `Point(-1, -1)`
> specorb: mouse off screen fix

- inferno/inferno.gradle.kts
- inferno/src/main/java/net/runelite/client/plugins/inferno/BlobDeathSpot.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoBlobDeathSpot.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoConfig.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoNPC.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoOverlay.java
- inferno/src/main/java/net/runelite/client/plugins/inferno/InfernoPlugin.java
- Adds an idle tick timer to InfernoNPC to track melees and give hints on their digging. Data collection tool being worked on to try and work out how their dig rng works.
- Adds a blob death location indicator to help with speeding when using entity hider extended
- Fix text rendering not setting font size before calculating canvas location. 
- typos
> inferno: melee dig timer & blob death indicator

- zulrah/src/main/java/net/runelite/client/plugins/zulrah/ZulrahPlugin.java
- zulrah/src/main/java/net/runelite/client/plugins/zulrah/rotationutils/ZulrahData.java
- zulrah/zulrah.gradle.kts
Fix: was showing wront prayer for the first jad attack.
My last zulrah fix inverted the prayers for the jad phase because the plugin was always incorrect in which to pray. Turns out the real core of the issue was that the flipped indicator was not properly updated at the start of jad phase. This means that the plugin was correct for all but the first attack. The plugin now shows proper prayers for the whole jad phase. 
-revert invert of prayers
-fix flipped bool
> zulrah: Fix jad phase prayers

- alchemicalhydra/alchemicalhydra.gradle.kts
- alchemicalhydra/src/main/java/net/runelite/client/plugins/alchemicalhydra/AlchemicalHydraPlugin.java
This delays setting immunity to later in the tick since onChatMessage events are sent before onAnimationChanged causing the plugin to show hydra as immune if the phase change finished as the vent triggered immunity for next phase.
> AlchemicalHydra: Delay setImmunity

- nex/nex.gradle.kts
- nex/src/main/java/net/runelite/client/plugins/nex/NexConfig.java
- nex/src/main/java/net/runelite/client/plugins/nex/NexOverlay.java
- nex/src/main/java/net/runelite/client/plugins/nex/NexPlugin.java
- nex/src/main/java/net/runelite/client/plugins/nex/maths/MathUtil.java
**changelog 5.0.6**
- add p1 dash lane detection (showing all you kids who don't like math and trig that it can be useful)
- dash support again because its big
- add nex range indicator for safespotting
- move tank earlier in drawing to not hide shadow spawns
- add zaros phase tank and prayer switch indicators
**Testing needed**
- is the tick counter on dash lane correct?
- is the immunity after dash correct?
- do the tank and pray indicators work as expected?
> nex: 5.0.6
